import type { ProcedureDef } from "../types";

// Septoplasty walkthrough. Axes (cm): +x = patient's left, +y = up, +z = anterior.
// The deviation in the model bends the septum toward the patient's left.

const ALL = { pele: 0, ossos: 1, cartilagens: 1, septo: 1, mucosa: 0, conchas: 1 };

export const septoplastia: ProcedureDef = {
  slug: "septoplastia",
  model: "/models/nariz.glb",

  layers: [
    { id: "pele", label: "Pele", swatch: "#E3B598" },
    { id: "ossos", label: "Ossos", swatch: "#EFE6D2" },
    { id: "cartilagens", label: "Cartilagens", swatch: "#BFD9DE" },
    { id: "septo", label: "Septo", swatch: "#9CC6D2" },
    { id: "mucosa", label: "Mucosa", swatch: "#D4757A" },
    { id: "conchas", label: "Conchas", swatch: "#C9868A" },
    { id: "ar", label: "Fluxo de ar", swatch: "#A9DDF0" },
  ],

  parts: [
    { match: /^pele$/, name: "Pele e tecidos moles", description: "Envoltório externo do nariz. A septoplastia é feita por dentro, sem cortes na pele.", layer: "pele", material: "skin", sagittalCut: true },
    { match: /^osso_nasal/, name: "Ossos nasais", description: "Formam a parte superior, óssea, do dorso do nariz.", layer: "ossos", material: "bone", sagittalCut: true },
    { match: /^maxila/, name: "Maxila", description: "Osso da face que forma as paredes laterais e o assoalho da cavidade nasal.", layer: "ossos", material: "bone", sagittalCut: true },
    { match: /^etmoide$/, name: "Etmoide", description: "Osso entre as órbitas. Forma o teto da cavidade nasal e as conchas média e superior.", layer: "ossos", material: "bone", sagittalCut: true },
    { match: /^palatino/, name: "Osso palatino", description: "Forma a parte de trás do assoalho do nariz (palato duro).", layer: "ossos", material: "bone", sagittalCut: true },
    { match: /^concha_inferior/, name: "Concha nasal inferior", description: "Estrutura revestida por mucosa que aquece, filtra e umidifica o ar. Quando aumentada, também pode piorar a obstrução.", layer: "conchas", material: "mucosa", tint: "#B25D73", sagittalCut: true },
    { match: /^cartilagem_lateral_superior/, name: "Cartilagem lateral superior", description: "Sustenta o terço médio do nariz. Junto com o septo forma a válvula nasal interna, a parte mais estreita da passagem de ar.", layer: "cartilagens", material: "cartilage", tint: "#B2D2E2", sagittalCut: true },
    { match: /^cartilagem_alar/, name: "Cartilagem alar", description: "Dá forma à ponta do nariz e sustenta as narinas.", layer: "cartilagens", material: "cartilage", tint: "#B2D2E2", sagittalCut: true },
    { match: /^septo_cartilagem_desvio$/, name: "Cartilagem septal (porção central)", description: "Parte central da cartilagem do septo. Quando está torta, é a porção retirada ou remodelada na cirurgia.", layer: "septo", material: "cartilage", tint: "#8FBDDF" },
    { match: /^septo_cartilagem$/, name: "Cartilagem septal (quadrangular)", description: "Parte da frente, flexível, do septo. Na cirurgia preserva-se uma estrutura em “L” de pelo menos 1 cm para manter a sustentação do nariz.", layer: "septo", material: "cartilage", tint: "#8FBDDF" },
    { match: /^lamina_perpendicular$/, name: "Lâmina perpendicular do etmoide", description: "Parte óssea, superior e posterior, do septo nasal.", layer: "septo", material: "bone" },
    { match: /^vomer$/, name: "Vômer", description: "Osso fino que forma a parte posterior e inferior do septo nasal.", layer: "septo", material: "bone" },
    { match: /^septo_osso_desvio$/, name: "Septo ósseo desviado (região do esporão)", description: "Região onde a cartilagem se encontra com o osso (vômer e lâmina perpendicular). Quando há desvio, costuma formar-se aqui uma crista (esporão) que pode encostar na concha.", layer: "septo", material: "bone" },
    { match: /^mucosa_septal/, name: "Mucosa do septo", description: "Revestimento úmido que cobre o septo dos dois lados (mucopericôndrio sobre a cartilagem e mucoperiósteo sobre o osso). Na cirurgia é descolado com cuidado, preservado e volta ao lugar.", layer: "mucosa", material: "mucosa", tint: "#DD9283" },
    { match: /^incisao$/, name: "Incisão", description: "Pequeno corte na mucosa, feito por dentro da narina. Não há cicatriz visível.", layer: "mucosa", material: "incision", optional: true },
    { match: /^splints$/, name: "Placas de silicone (splints)", description: "Placas finas que mantêm o septo na linha média nos primeiros dias. São retiradas no consultório.", layer: "septo", material: "silicone", optional: true },
    { match: /^suturas$/, name: "Pontos absorvíveis", description: "Aproximam a mucosa do septo e evitam acúmulo de sangue. São absorvidos pelo organismo.", layer: "mucosa", material: "suture", optional: true },
    // Coronal slice (corte_*): closed solids whose front face lies at z = -1.6. Hidden unless a step's partOpacity shows them.
    { match: /^corte_osso$/, name: "Osso da parede do nariz", description: "Maxila e palatino: formam o assoalho e a parede lateral da cavidade nasal.", layer: "ossos", material: "bone", optional: true },
    { match: /^corte_concha_media/, name: "Concha nasal média", description: "Estrutura da parede lateral do nariz, acima da concha inferior, também revestida por mucosa. Ajuda a condicionar o ar e a direcioná-lo pela cavidade nasal.", layer: "conchas", material: "mucosa", tint: "#B25D73", optional: true },
    { match: /^corte_concha/, name: "Concha nasal inferior", description: "Estrutura revestida por mucosa que aquece, filtra e umidifica o ar. Quando aumentada, também pode piorar a obstrução.", layer: "conchas", material: "mucosa", optional: true },
    { match: /^corte_septo_cartilagem$/, name: "Cartilagem septal (quadrangular)", description: "Parte da frente, flexível, do septo nasal.", layer: "septo", material: "cartilage", optional: true },
    { match: /^corte_septo_osso$/, name: "Septo ósseo (lâmina perpendicular e vômer)", description: "Parte óssea, superior e posterior, do septo nasal.", layer: "septo", material: "bone", optional: true },
    { match: /^corte_mucosa/, name: "Mucosa", description: "Revestimento úmido que cobre o septo e as paredes da cavidade nasal.", layer: "mucosa", material: "mucosa", optional: true },
    { match: /^corte_ar/, name: "Passagem de ar", description: "Espaço livre por onde o ar passa em cada lado do nariz. Com o septo desviado, o lado esquerdo fica mais estreito.", layer: "ar", material: "air", optional: true },
  ],

  labels: [
    { id: "ossos_nasais", text: "Ossos nasais", anchor: [0.29, 2.38, -0.01], layer: "ossos" },
    { id: "lateral_superior", text: "Cartilagem lateral superior", anchor: [0.4, 0.48, 1.3], layer: "cartilagens" },
    { id: "alar", text: "Cartilagem alar", anchor: [1.05, -1.25, 1.75], layer: "cartilagens" },
    { id: "cartilagem_septal", text: "Cartilagem quadrangular", anchor: [0.12, -0.2, 1.4], layer: "septo" },
    { id: "lamina", text: "Lâmina perpendicular do etmoide", anchor: [0.1, 2.3, -2.4], layer: "septo" },
    { id: "vomer", text: "Vômer", anchor: [0.1, 0.35, -4.9], layer: "septo" },
    { id: "desvio", text: "Septo desviado", anchor: [0.2, 0.0, -2.5], layer: "septo" },
    { id: "concha", text: "Concha inferior", anchor: [1.0, -0.3, -2.5], layer: "conchas" },
    { id: "lado_obstruido", text: "Lado esquerdo estreitado", anchor: [0.6, 0.3, -2.66], layer: "ar", side: "right" },
    { id: "incisao", text: "Incisão por dentro da narina", anchor: [0.32, -0.45, 1.8], layer: "mucosa" },
    { id: "retalho", text: "Mucosa descolada", anchor: [0.75, 0.6, -0.6], layer: "mucosa" },
    { id: "l_strut", text: "Estrutura em “L” preservada", anchor: [0.14, 0.9, 1.25], layer: "septo" },
    { id: "splints", text: "Placa de silicone", anchor: [0.45, -0.95, -0.4], layer: "septo" },
    { id: "suturas", text: "Pontos absorvíveis", anchor: [0.35, 0.15, 0.6], layer: "mucosa", side: "left" },
    { id: "centralizado", text: "Septo centralizado", anchor: [0.1, 1.4, -2.5], layer: "septo", side: "left" },
    { id: "ar_dois_lados", text: "Ar pelos dois lados", anchor: [0.85, 0.75, -2.66], layer: "ar", side: "right" },
  ],

  // Control points of Catmull-Rom streams (cm). Generated by scripts/anatomy/route-airflow.mjs: every
  // stream keeps >= 0.12 cm from every mesh with the septum straight AND deviated (asserted by
  // scripts/anatomy/check.mjs on every build). Entry at the nostril, exit at the choana.
  airflow: [
    { side: "right", points: [[-0.8, -2.6, 2.2], [-0.62, -1.62, 0.79], [-0.66, -0.3, -0.52], [-0.86, 0.8, -1.85], [-1.07, 0.55, -3.5], [-0.65, -0.57, -4.85], [-0.62, -0.52, -6.65], [-0.4, -0.3, -6.9]] },
    { side: "right", points: [[-0.8, -2.6, 2.2], [-0.62, -1.62, 0.79], [-0.67, -0.91, -0.8], [-0.54, -1.08, -2.6], [-0.61, -1.1, -4.4], [-0.7, -1.1, -6.2], [-0.4, -1, -6.9]] },
    { side: "left", points: [[0.8, -2.6, 2.2], [0.57, -1.62, 0.79], [0.85, -0.8, -0.73], [0.77, 0.57, -1.55], [0.89, 0.6, -3.3], [0.5, -0.34, -4.75], [0.69, -0.45, -6.5], [0.4, -0.3, -6.9]], narrowing: [0.2, 0.5] },
    { side: "left", points: [[0.8, -2.6, 2.2], [0.57, -1.62, 0.79], [0.67, -1.05, -0.9], [0.55, -1.25, -2.7], [0.55, -1.15, -4.5], [0.55, -1.15, -6.3], [0.4, -1, -6.9]], narrowing: [0.2, 0.5] },
  ],

  obstructionMorph: "desvio",

  steps: [
    {
      id: "anatomia",
      short: "Anatomia",
      title: "Por dentro do nariz",
      body: "Por baixo da pele, o nariz tem um arcabouço de ossos (na parte de cima) e de cartilagens (no meio e na ponta). Por dentro, o septo divide a cavidade nasal em dois lados, e as conchas nasais aquecem e umidificam o ar. Gire o modelo e toque em qualquer estrutura para ver o nome.",
      camera: { position: [5.6, 1.7, 17.9], target: [0, 0.7, 0] },
      portraitZoom: 0.68,
      layers: { ...ALL, pele: 0.5, conchas: 0 },
      partOpacity: { "^(maxila|palatino|etmoide)": 0.0 },
      labels: ["ossos_nasais", "lateral_superior", "alar"],
    },
    {
      id: "septo",
      short: "O septo",
      title: "A parede que divide o nariz",
      body: "O septo tem uma parte de cartilagem na frente — a cartilagem quadrangular — e uma parte óssea atrás, formada pela lâmina perpendicular do etmoide e pelo vômer. Nesta vista, o lado esquerdo do rosto foi removido para mostrar o septo de perfil. Na vida real, ele é todo revestido por mucosa.",
      camera: { position: [16, 1.1, -0.9], target: [0, 0.8, -1.7] },
      layers: { ...ALL },
      cut: { sagittal: 0.3 },
      labels: ["cartilagem_septal", "lamina", "vomer"],
      partOpacity: { "^osso_nasal": 0.4 },
    },
    {
      id: "desvio",
      short: "O desvio",
      title: "Quando o septo está desviado",
      body: "Se o septo se curva para um dos lados, aquele lado fica estreito e o ar passa com dificuldade. Isso pode causar nariz entupido constante, respiração pela boca, ronco e sono de pior qualidade. Neste corte, visto de frente, o septo se curva para a esquerda e se aproxima da concha desse lado, estreitando a passagem de ar. Nem todo desvio precisa de cirurgia: a indicação depende dos sintomas e do exame.",
      camera: { position: [2.6, 3.4, 12], target: [0, 0.9, -2.5] },
      portraitZoom: 0.9,
      layers: { ...ALL, mucosa: 1, ar: 1 },
      morphs: { desvio: 1 },
      partOpacity: { "^(?!corte_)": 0, "^corte_": 1, "^corte_ar": 0.72 },
      particles: false,
      highlight: ["^corte_septo_cartilagem$"],
      labels: ["desvio", "concha", "lado_obstruido"],
    },
    {
      id: "incisao",
      short: "Incisão",
      title: "Acesso por dentro da narina",
      body: "A septoplastia é feita por dentro do nariz: não há cortes na pele e o formato externo não muda. Uma pequena incisão é feita na mucosa, perto da parte da frente do septo.",
      camera: { position: [9, -1.4, 7.5], target: [0.2, -0.5, 0.9] },
      layers: { ...ALL, mucosa: 1, ossos: 0, conchas: 0 },
      morphs: { desvio: 1 },
      cut: { sagittal: 0.3, coronalBack: -1.9 },
      partOpacity: { "^incisao$": 1, "^mucosa_septal_esq": 0.55, "^mucosa_septal_dir$": 0 },
      highlight: ["^incisao$"],
      labels: ["incisao"],
    },
    {
      id: "descolamento",
      short: "Descolamento",
      title: "A mucosa é descolada e preservada",
      body: "Com delicadeza, a mucosa é descolada da cartilagem e do osso de um lado e, depois, do outro, como se abríssemos um envelope (aqui afastada para facilitar a visualização). Assim o septo fica acessível sem retirar o revestimento, que volta ao lugar no final.",
      camera: { position: [7, 3, 10.5], target: [0.4, 0.2, -0.2] },
      layers: { ...ALL, mucosa: 1, ossos: 0, conchas: 0 },
      morphs: { desvio: 1, descolamento: 1 },
      cut: { sagittal: 0.3, coronalBack: -3.4 },
      partOpacity: { "^mucosa_septal_esq$": 0.6, "^mucosa_septal_dir$": 0, "^cartilagem_alar": 0, "^incisao$": 1 },
      highlight: ["^mucosa_septal_esq$"],
      labels: ["retalho"],
    },
    {
      id: "correcao",
      short: "Correção",
      title: "A parte desviada é retirada ou remodelada",
      body: "A região torta da cartilagem e o esporão ósseo são retirados ou remodelados; em desvios maiores, isso pode ser uma área extensa. Uma estrutura em forma de “L” — com pelo menos 1 cm ao longo do dorso e da parte da frente do septo — é preservada para manter a sustentação e a aparência do nariz.",
      camera: { position: [13, 1.2, 4.5], target: [0, 0.2, -0.8] },
      layers: { ...ALL, mucosa: 1, ossos: 0, conchas: 0 },
      morphs: { desvio: 1, descolamento: 1 },
      cut: { sagittal: 0.3 },
      pieces: { septo_cartilagem_desvio: { out: 1 }, septo_osso_desvio: { out: 1 } },
      partOpacity: { "^mucosa_septal_esq": 0, "^mucosa_septal_dir$": 1, "^cartilagem_alar": 0, "^incisao$": 1 },
      highlight: ["^septo_cartilagem$"],
      labels: ["l_strut"],
    },
    {
      id: "fechamento",
      short: "Fechamento",
      title: "Septo reto e mucosa no lugar",
      body: "O septo remanescente é reposicionado e fixado na linha média. A cartilagem retirada pode ser retificada e recolocada entre as camadas de mucosa. A mucosa volta ao lugar e é fixada com pontos absorvíveis, que também fecham a incisão. Placas finas de silicone podem ser mantidas por alguns dias.",
      camera: { position: [14, 1.2, 4.5], target: [0, -0.3, 0] },
      layers: { ...ALL, mucosa: 1, ossos: 0, conchas: 0 },
      cut: { sagittal: 0.3, coronalBack: -1.9 },
      pieces: { septo_cartilagem_desvio: { out: 0, scale: 0.9 }, septo_osso_desvio: { out: 1 } },
      partOpacity: { "^splints$": 0.7, "^suturas$": 1, "^mucosa_septal_esq": 0.88, "^mucosa_septal_dir$": 1 },
      highlight: ["^splints$", "^suturas$"],
      labels: ["splints", "suturas"],
    },
    {
      id: "resultado",
      short: "Resultado",
      title: "Ar passando pelos dois lados",
      body: "Com o septo centralizado, o ar tende a passar com mais facilidade pelos dois lados do nariz. Nas primeiras semanas é normal sentir o nariz congestionado por causa do inchaço; a melhora da respiração aparece de forma progressiva.",
      camera: { position: [2.6, 3.4, 12], target: [0, 0.9, -2.5] },
      portraitZoom: 0.9,
      layers: { ...ALL, mucosa: 1, ar: 1 },
      partOpacity: { "^(?!corte_)": 0, "^corte_": 1, "^corte_ar": 0.72 },
      particles: false,
      labels: ["centralizado", "ar_dois_lados"],
    },
  ],
};
